{{- $releaseName := .Release.Name -}}
{{- $chartName := include "cleaner.name" . -}}
{{- $cloudProviderFlavor := include "cleaner.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "cleaner.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "cleaner.cloudProviderImagePullSecretName" . -}}
{{- $imageTag := include "cleaner.tag" . -}}
{{- $ca := fromYaml (include "common.ca.merged" .) -}}
{{- $storage := fromYaml (include "common.storage.merged" .) -}}
{{- $s3 := ($storage.s3) | default dict -}}
{{- $internalPvc := (($storage.fs).internalPvc) | default dict -}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-deployment" (include "cleaner.fullname" .) }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    release: {{ $releaseName }}
    {{- include "cleaner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "cleaner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "cleaner.labels" . | nindent 8 }}
      annotations:
        {{ include "mclabels.annotations" . | nindent 8 }}
      {{- if .Values.resetOnConfigChange }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
      {{- if .Values.podAnnotations }}
      {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
    {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
    {{- end }}
      containers:
        - name: {{ $releaseName }}-{{ $chartName }}-deployment
          {{- with .Values.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $imageTag }}
          imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
          {{- end }}
          {{- if .Values.command }}
          command: 
          {{- toYaml .Values.command | nindent 12 }}
          {{- if .Values.args }}
          args: 
          {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          {{- end }}
          volumeMounts:
            {{- if $ca.secretName }}
            - mountPath: {{ printf "%s/%s" $ca.path $ca.key | quote }}
              name: root-ca
              subPath: {{ quote $ca.key }}
            {{- end }}
            {{- if .Values.extraVolumeMounts -}}
              {{ toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
            {{- if $internalPvc.enabled }}
            - name: internal-pvc
              mountPath: {{ $internalPvc.mountPath | quote }}
            {{- end }}
          env:
            - name: K8S_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: SERVER_PORT
              value: {{ .Values.env.targetPort | quote }}
            {{- if $ca.secretName }}
            - name: REQUESTS_CA_BUNDLE
              value: {{ printf "%s/%s" $ca.path $ca.key | quote }}
            - name: NODE_EXTRA_CA_CERTS
              value: {{ printf "%s/%s" $ca.path $ca.key | quote }}
            {{- end }}
            {{- if $s3.secretName }}
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $s3.secretName }}
                  key: accessKeyId
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $s3.secretName }}
                  key: secretAccessKey
            {{- end }}
            {{- if .Values.extraEnvVars }}
            {{- toYaml .Values.extraEnvVars | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-configmap" (include "cleaner.fullname" .) }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.env.targetPort }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.env.targetPort }}
          {{- end }}        
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
        {{- if .Values.sidecars }}
        {{ tpl (toYaml .Values.sidecars) . | nindent 8 }}
        {{- end }}
      volumes:
        {{- if $ca.secretName }}
        - name: root-ca
          secret:
            secretName: {{ $ca.secretName }}
        {{- end }}
        {{- if .Values.extraVolumes -}}
          {{ tpl (toYaml .Values.extraVolumes) . | nindent 8 }}
        {{- end }}
        {{- if $internalPvc.enabled }}
        - name: internal-pvc
          persistentVolumeClaim:
            claimName: {{ $internalPvc.name }}
        {{- end }}
{{- end -}}
