global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  jobDefinitions: {}
  storage: {}
  serviceUrls: {}
  ca: {}

serviceUrls:
  jobManager: ""
  heartbeatManager: ""
  jobTracker: ""

storage:
  cleanupStorageProviders:
    - FS
    - S3
  s3:
    endpointUrl: ""
    forcePathStyle: true
    secretName: ""
    sslEnabled: false
    region: ""
    tilesBucket: ""
  fs:
    internalPvc:
      enabled: false
      name: ""
      mountPath: ""
      tilesSubPath: ""


mclabels:
  component: backend
  partOf: core
  owner: raster
  prometheus:
    enabled: true

enabled: true
replicaCount: 1
revisionHistoryLimit: 5  # Amount of revisions we keep
nodePort: 30030  # for minikube deployment only
resetOnConfigChange: false

nameOverride: ""
fullnameOverride: ""

configManagement:
  offlineMode: false
  name: 'cleaner'
  version: ''
  serverUrl: ''

jobDefinitions: {}

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  path: /liveness

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  path: /liveness

podAnnotations: {}

extraVolumes: []

extraVolumeMounts: []

extraEnvVars: []

command: []
args: []
# command: [ "/bin/sh", "-c", "--" ]
# args: [ "while true; do sleep infinity; done;" ]

sidecars: []

cloudProvider:
  dockerRegistryUrl: ''
  imagePullSecretName: ''
  flavor: openshift

ca:
  secretName: ''
  path: '/usr/local/share/ca-certificates'
  key: 'ca.crt'

image:
  repository: cleaner
  # If commented, appVersion will be taken. See: _helpers.tpl
  # tag: 'latest'
  pullPolicy: IfNotPresent

env:
  port: 8080
  logLevel: info
  prettyPrintEnabled: false
  openTelemetryOptions:
    enabled: false
    url: ""
    resourceAttributes: {}
  tracing:
    enabled: false
    url: ""
  queue:
    heartbeatIntervalMs: 1000
    dequeueIntervalMs: 3000
  worker:
    capabilities:
      pairs:
        - job: "Ingestion_Update"
          task: "tiles-deletion"
        - job: "Ingestion_Swap_Update"
          task: "tiles-deletion"
  httpRetry:
    attempts: 3
    delay: "exponential"
    shouldResetTimeout: true
  disableHttpClientLogs: false
  strategies:
    tilesDeletion:
      batchSize: 1000
      concurrency: 10
      failureSampleSize: 3
    storedResourcesDeletion:
      failureSampleSize: 3

resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
