global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  jobDefinitions: {}


mclabels:
  component: backend
  partOf: core
  owner: raster
  prometheus:
    enabled: true

enabled: true
replicaCount: 1
revisionHistoryLimit: 5  # Amount of revisions we keep
nodePort: 30030  # for minikube deployment only
resetOnConfigChange: false

nameOverride: ""
fullnameOverride: ""

configManagement:
  offlineMode: false
  name: 'cleaner'
  version: 'latest'
  serverUrl: 'http://localhost:8080/api'

jobDefinitions: {}

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  path: /liveness

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  path: /liveness

podAnnotations: {}

extraVolumes: []

extraVolumeMounts: []

extraEnvVars: []

command: []
args: []
# command: [ "/bin/sh", "-c", "--" ]
# args: [ "while true; do sleep infinity; done;" ]

sidecars: []

cloudProvider:
  dockerRegistryUrl: ''
  imagePullSecretName: ''
  flavor: openshift

caSecretName: ''
caPath: '/usr/local/share/ca-certificates'
caKey: 'ca.crt'

image:
  repository: cleaner
  # If commented, appVersion will be taken. See: _helpers.tpl
  # tag: 'latest'
  pullPolicy: IfNotPresent

env:
  port: 8080
  logLevel: info
  logPrettyPrintEnabled: false
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  queue:
    jobManagerBaseUrl: "http//localhost:8080"
    heartbeatBaseUrl: "http//localhost:8081"
    heartbeatIntervalMs: 1000
    dequeueIntervalMs: 3000
  worker:
    capabilities:
      pairs:
        - job: "Ingestion_Update"
          task: "tiles-deletion"
        - job: "Ingestion_Swap_Update"
          task: "tiles-deletion"    
  httpRetry:
    attempts: 3
    delay: "exponential"
    shouldResetTimeout: true

resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
